#!/bin/bash
# -*- mode sh -*-
#
# ОПИСАНИЕ: Показывает информацию о pdf файле
#
# ЗАВИСИТ:  yad 12.3 (GTK+ 3.24.36)
#           pdfinfo version 23.01.0
#           GNU Awk 5.2.1, API 3.2, PMA Avon 8-g1, (GNU MPFR 4.2.0, GNU MP 6.2.1)
#           grep (GNU grep) 3.8

SCRIPT_NAME='pdfInfo'
TITLE_DIALOG=${0##*/}
SCRIPT_DIR=${0%/*}
ICON_DIR=$(readlink -e "$SCRIPT_DIR"/../../icons)
ICONS=$ICON_DIR/menu-pdf.svg

export YAD_OPTIONS="--window-icon $ICONS --name $SCRIPT_NAME"

notifyDialog() {
  yad --geometry 100x50-10+50 --no-buttons --undecorated --skip-taskbar \
    --close-on-unfocus --timeout 5 \
    --text "\n$TEXT_DIALOG\n" --text-align center --text-width 30
}

if [ ${#@} -ne 1 ]; then

  # Если выбрали более одного файла, сообщить об ошибке
  TEXT_DIALOG='Выберите только один файл в формате pdf.'
  notifyDialog

else

  # Псевдоним имени файла
  file_name=$1

  # Получить mime-type файла для проверки выбора файла
  file_type=$(file --mime-type "$file_name" | awk -F": " '{print $2}')

  if [ "$file_type" != 'application/pdf' ]; then

    # Если файл не в формате pdf, сообщить об ошибке
    TEXT_DIALOG='Для просмотра информации о документе, '
    TEXT_DIALOG+='выберите файл в формате pdf.'
    notifyDialog

  else

    # Получить информацию о документе
    info_pdf=$(pdfinfo "$file_name")

    # Получить заголовок документа
    title_pdf=$(echo "$info_pdf" | grep -E "^Title:" |
      awk -F': *' '{print $2}')

    # Если заголовок не получили, установить в качестве заголовка имя файла
    TEXT_DIALOG=${title_pdf:-$file_name}

    # Показать информацию о pdf файле
    echo "$info_pdf" | sed -r 's/:[ ]*/\n/' |
      yad --geometry 450x600+200+100 --title "$TITLE_DIALOG" \
        --button yad-close --text "$TEXT_DIALOG" \
        --list --grid-lines both --no-selection \
        --column Tag --column Value

  fi

fi
